### ISSUE TITLE
可以添加个使用说明吗

### ISSUE THREAD

**Issue by SmallRedSister** [DayorNight/BLCS#1]
写的不错，666
可以增加个网络状态判断吗？比如 ：用户连接的是WiFi还是数据流量。

**Comment by DayorNight** [comment]
![image](https://user-images.githubusercontent.com/20598713/64085713-f6a6de00-cd66-11e9-9caa-c8d8d0c503e5.png)
可以试下  1.工具-> LinNetStatus   -> 获取网络状态   是不是符合您的需求
因为项目东西比较杂 都是单一的Demo模式 所以暂时没有相关的说明 目前只能通过项目代码了解使用方式

**Comment by SmallRedSister** [comment]
好的ヽ(￣▽￣)و
