### ISSUE TITLE
蒲公英下载的密码是什么？

### ISSUE THREAD

**Issue by zhoujia456888** [DayorNight/BLCS#3]
扫描二维码跳转到蒲公英，提示要下载密码。
![微信图片_20200105174115](https://user-images.githubusercontent.com/7905253/71777979-9b218100-2fe2-11ea-9259-4baa4da41990.jpg)

**Comment by lidexin-aldelo** [comment]
看标题

**Comment by DayorNight** [comment]
蒲公英下载密码：BLCS

**Comment by zijin2014** [comment]
蒲公英已经不让下载了
